appenders:
  file:
    kind: file
    path: 'logs/sync.log'
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
  stdout:
    kind: console

root:
  level: debug
  appenders:
    - file
    - stdout